### ISSUE TITLE
No matching export for import "default"

### ISSUE THREAD

**Issue by iamareebjamal** [nuxt/vite#11]
```
Server compiled with errors: Build failed with 1 error:                                                                                                         04:20:57
.nuxt/index.js:16:7: error: No matching export for import "default"

  .nuxt/index.js:16:7: error: No matching export for import "default"
  at failureErrorWithLog (node_modules/esbuild/lib/main.js:1171:15)
  at buildResponseToResult (node_modules/esbuild/lib/main.js:907:32)
  at node_modules/esbuild/lib/main.js:1002:20
  at node_modules/esbuild/lib/main.js:553:9
  at handleIncomingPacket (node_modules/esbuild/lib/main.js:642:9)
  at Socket.readFromStdout (node_modules/esbuild/lib/main.js:520:7)
  at Socket.emit (events.js:315:20)
  at addChunk (_stream_readable.js:309:12)
  at readableAddChunk (_stream_readable.js:284:9)
  at Socket.Readable.push (_stream_readable.js:223:10)
  at Pipe.onStreamRead (internal/stream_base_commons.js:188:23
```

   |   Nuxt @ v2.15.2                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   server-side          │
   │   ▸ Target:      static               |

**Comment by pi0** [comment]
Hi @iamareebjamal. Would you please create a small reproduction repo?

**Comment by iamareebjamal** [comment]
https://github.com/iamareebjamal/nuxt-vite-bug

**Comment by danielroe** [comment]
I think it's likely same as #13 and #12.

**Comment by Pramod-Devireddy** [comment]
facing the same issue.

**Comment by productfrontenddeveloper** [comment]
Some problem
![Screen Shot 2021-02-26 at 07 21 44](https://user-images.githubusercontent.com/38668796/109254545-4868e100-7803-11eb-9d1b-0a1e8205a7ee.png)

**Comment by standfv** [comment]
How to fix?

**Comment by iamareebjamal** [comment]
Wait for new release. @pi0 Tests are broken after the merge

**Comment by kissu** [comment]
@standfv will probably be available in the next release. Wait for like, idk 2min ?!

**Comment by standfv** [comment]
> @standfv will probably be available in the next release. Wait for like, idk 2min ?!

Ok. Thank you.

**Comment by pi0** [comment]
I have tried to address in #20 but 98983c8f357a8d0f4af786c7c5b884189074e2bd but seems vite still sometimes is ignoring required hooks to support default export.... Trying to figure out. Any solution more than welcome :D

**Comment by pi0** [comment]
Should be fixed by 0.0.5. If not please share steps to reproduce.

**Comment by iamareebjamal** [comment]
Custom plugin import doesn't work.

```
[nuxt:default-export] Could not load defaultexport:/home/iamareebjamal/git/nuxt-vite-bug/plugins/test (imported by .nuxt/index.js): ENOENT: no such file or directory, open '/home/iamareebjamal/git/nuxt-vite-bug/plugins/test'
```

Should I open another issue?

Repro: https://github.com/iamareebjamal/nuxt-vite-bug

**Comment by productfrontenddeveloper** [comment]
0.0.5.  -> [vite] Internal server error: ENOENT: no such file or directory, open '/my-project/plugins/axios'

**Comment by pi0** [comment]
Thanks for reproduction @iamareebjamal.  Vite requires extensions (`~/plugins/test.js`). You can now import plugins without `.js` with 0.0.6. (note other modules like vuetify might be broken)

**Comment by productfrontenddeveloper** [comment]
0.0.6

``` ERROR  'default' is not exported by .nuxt/content/query-builder.js, imported by defaultexport:/my-project/.nuxt/content/plugin.client.js


 ERROR  file: defaultexport:/my-project/.nuxt/content/plugin.client.js:3:7                                                        15:57:53


 ERROR  1: import Vue from 'vue'                                                                                                                                       15:57:53
2: import NuxtContent from './nuxt-content.dev'
3: import QueryBuilder from './query-builder'
          ^
4: 
5: Vue.component(NuxtContent.name, NuxtContent)


 ERROR  Server compiled with errors: 'default' is not exported by .nuxt/content/query-builder.js, imported by defaultexport:/my-project/.nuxt/content/plugin.client.js

  at error (node_modules/rollup/dist/shared/rollup.js:5275:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:9992:16)
  at Module.traceVariable (node_modules/rollup/dist/shared/rollup.js:10385:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/shared/rollup.js:8843:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/shared/rollup.js:2637:38)
  at ChildScope.findVariable (node_modules/rollup/dist/shared/rollup.js:2637:38)
  at FunctionScope.findVariable (node_modules/rollup/dist/shared/rollup.js:2637:38)
  at ChildScope.findVariable (node_modules/rollup/dist/shared/rollup.js:2637:38)
  at Identifier$1.bind (node_modules/rollup/dist/shared/rollup.js:4013:40)
  at NewExpression$1.bind (node_modules/rollup/dist/shared/rollup.js:2724:23)
  at NewExpression$1.bind (node_modules/rollup/dist/shared/rollup.js:8100:15)
  at ReturnStatement$1.bind (node_modules/rollup/dist/shared/rollup.js:2724:23)
  at BlockStatement$1.bind (node_modules/rollup/dist/shared/rollup.js:2720:31)
  at FunctionExpression.bind (node_modules/rollup/dist/shared/rollup.js:2724:23)
  at VariableDeclarator.bind (node_modules/rollup/dist/shared/rollup.js:2724:23)
  at VariableDeclaration.bind (node_modules/rollup/dist/shared/rollup.js:2720:31)
```

**Comment by pi0** [comment]
See #14
