### ISSUE TITLE
Transforming destructuring to the configured target environment is not supported yet

### ISSUE THREAD

**Issue by chrispreisler** [nuxt/vite#110]
### Versions

nuxt-vite: v0.0.36 
nuxt: v2.15.3

### Reproduction
https://codesandbox.io/s/beautiful-cohen-7fc42?file=/nuxt.config.js

### Description

Hey guys,

I tried to add Nuxt-Vite to a fresh installed nuxt app. Unfortunately I get this errors. It only happens, when ssr is enabled. Is ssr even supported? Above you find a reproduction sandbox link.

Thank you very much for looking into that.

Best regards
Chris

 ```
ERROR  Transform failed with 24 errors:                                                                                                                                     15:01:43
server.js:250:10: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
server.js:316:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
server.js:317:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
server.js:318:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
server.js:329:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
...

  server.js:250:10: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
  server.js:316:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
  server.js:317:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
  server.js:318:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
  server.js:329:8: error: Transforming destructuring to the configured target environment ("chrome61", "edge16", "es2019", "firefox60", "safari11") is not supported yet
  ...
  at failureErrorWithLog (node_modules/esbuild/lib/main.js:1195:15)
  at node_modules/esbuild/lib/main.js:1056:33
  at node_modules/esbuild/lib/main.js:566:9
  at handleIncomingPacket (node_modules/esbuild/lib/main.js:655:9)
  at Socket.readFromStdout (node_modules/esbuild/lib/main.js:533:7)
  at Socket.emit (events.js:315:20)
  at addChunk (_stream_readable.js:295:12)
  at readableAddChunk (_stream_readable.js:271:9)
  at Socket.Readable.push (_stream_readable.js:212:10)
  at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by Saravia83c** [comment]
#- [ ] - @💋

**Comment by TamPhamdev** [comment]
Any update? I have same issue.

**Comment by Ayfri** [comment]
Same.

**Comment by GiancarlosIO** [comment]
👀

**Comment by maurer2** [comment]
Hello, using edge18 or newer instead of edge16 should work. Here's an example for syandalone vite.config.ts

```ts
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'

export default defineConfig(({ command }) => {
    if (command === 'serve') {
        return {
            plugins: [vue()]
        }
    } else {
        return {
            plugins: [vue()],
            build: {
                target: ['chrome60', 'firefox60', 'safari11', 'edge18']
            }
        }
    }
})

```
This can probably set in nuxt as well (https://vite.nuxtjs.org/getting-started/config)

**Comment by CamilleAbella** [comment]
> 
> 
> Same.

Me too :octocat:

**Comment by Saravia83c** [comment]
>   #@_n_

**Comment by mryechkin** [comment]
> using edge18 or newer as a build target instead of edge16 should work

Not a Vite user, but this solved my issue with this exact error in a standalone `esbuild` project. Thanks @maurer2!
