### ISSUE TITLE
error on load file .graphql

### ISSUE THREAD

**Issue by Rasool-deldar** [nuxt/vite#112]
When the graphql file loads on the server run console it says please fix this problem.

 ERROR  [rollup-plugin-dynamic-import-variables] Unexpected token (1:6)                                                                                                                                                   12:36:18

 ERROR  file: {pathProject}/graphql/categories/queries/categoryAll.graphql:1:6                                                                                          12:36:18

 ERROR  Unexpected token (1:6)                                                                                                                                                                                            12:36:18

  at Object.pp$4.raise (node_modules\rollup\dist\shared\rollup.js:15592:13)
  at Object.pp.unexpected (node_modules\rollup\dist\shared\rollup.js:13284:8)
  at Object.pp.semicolon (node_modules\rollup\dist\shared\rollup.js:13261:64)
  at Object.pp$1.parseExpressionStatement (node_modules\rollup\dist\shared\rollup.js:13740:8)
  at Object.pp$1.parseStatement (node_modules\rollup\dist\shared\rollup.js:13475:24)
  at Object.pp$1.parseTopLevel (node_modules\rollup\dist\shared\rollup.js:13341:21)
  at Object.parse (node_modules\rollup\dist\shared\rollup.js:13143:15)
  at Function.parse (node_modules\rollup\dist\shared\rollup.js:13164:35)
  at Graph.contextParse (node_modules\rollup\dist\shared\rollup.js:19241:38)
  at Object.transform (node_modules\vite\dist\node\chunks\dep-efe32886.js:31400:27)
  at Object.<anonymous> (node_modules\vite\dist\node\chunks\dep-efe32886.js:44356:33)
  at node_modules\rollup\dist\shared\rollup.js:18804:25

**Comment by dpschen** [comment]
@Rasool-deldar see: https://vite.nuxtjs.org/misc/common-issues#graphql-support
