### ISSUE TITLE
issue with `@nuxtjs/composition-api`

### ISSUE THREAD

**Issue by PawaOx4th** [nuxt/vite#123]
nuxt-vite: 
nuxt: 
nuxt-composition api :  https://composition-api.nuxtjs.org/
![image](https://user-images.githubusercontent.com/41177171/114852808-543d5080-9e0d-11eb-9eed-bee010cec3e0.png)

**Comment by ChangJoo-Park** [comment]
issue with @nuxtjs/composition-api here.

```
√ Builder initialized                                                                                                                                                   
√ Nuxt files generated                                                                                                                                                  
 > .nuxt/middleware.js:1:7: error: No matching export in ".nuxt/composition-api/register.js" for import "default"
    1 │ import $c289ad42 from '.\\composition-api\\register.js'
      ╵        ~~~~~~~~~


 ERROR  Build failed with 1 error:                                                                                                                                        
.nuxt/middleware.js:1:7: error: No matching export in ".nuxt/composition-api/register.js" for import "default"

  .nuxt/middleware.js:1:7: error: No matching export in ".nuxt/composition-api/register.js" for import "default"
  at failureErrorWithLog (node_modules\esbuild\lib\main.js:1224:15)
  at buildResponseToResult (node_modules\esbuild\lib\main.js:936:32)
  at node_modules\esbuild\lib\main.js:1035:20
  at node_modules\esbuild\lib\main.js:568:9
  at handleIncomingPacket (node_modules\esbuild\lib\main.js:657:9)
  at Socket.readFromStdout (node_modules\esbuild\lib\main.js:535:7)
  at Socket.emit (events.js:315:20)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)```
