### ISSUE TITLE
Error: Template src not found

### ISSUE THREAD

**Issue by ririen** [nuxt/vite#137]
### Versions

nuxt-vite: 0.0.38
nuxt-edge: 2.16.0-27010091.9de997f1

### Reproduction
`yarn dev`

```bash
🧪  Vite mode is experimental and many nuxt modules are still incompatible                                                                                                           00:03:11
    If found a bug, please report via https://github.com/nuxt/vite/issues with a minimal reproduction

 FATAL  Template src not found: /home/ririen/Projekty/bitcoin-pl/bitcoin.pl/node_modules/nuxt-vite/dist/runtime/templates/store.js                                                   00:03:11

  at ModuleContainer.addTemplate (node_modules/@nuxt/core-edge/dist/core.js:78:13)
  at ModuleContainer.nuxtVite (node_modules/nuxt-vite/dist/nuxt-vite.js:35:10)
  at ModuleContainer.addModule (node_modules/@nuxt/core-edge/dist/core.js:239:34)
  at node_modules/@nuxt/utils-edge/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core-edge/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core-edge/dist/core.js:478:5)


   ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                       │
   │   ✖ Nuxt Fatal Error                                                                                                                  │
   │                                                                                                                                       │
   │   Error: Template src not found: /home/ririen/Projekty/bitcoin-pl/bitcoin.pl/node_modules/nuxt-vite/dist/runtime/templates/store.js   │
   │                                                                                                                                       │
   ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Description

This error only occurs in version 0.0.38, version 0.0.37 works normally.

**Comment by pi0** [comment]
Hi. Thanks for issue. Should be fixed in 0.0.39. please reopen if not.
