### ISSUE TITLE
error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "fs". 

### ISSUE THREAD

**Issue by kanagucalmet** [nuxt/vite#160]
error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json
while running my exisiting nuxtjs app with vitejs

**Comment by kanagucalmet** [comment]
🧪  Vite mode is experimental and some nuxt modules might be incompatible                                                                                                                                                            11:31:17
    If found a bug, please report via https://github.com/nuxt/vite/issues with a minimal reproduction.
    Unstable server-side rendering is enabled

 WARN  Address 0.0.0.0:5000 is already in use.                                                                                                                                                                                       11:31:20

ℹ Trying a random port...                                                                                                                                                                                                            11:31:20

   ╭────────────────────────────────────────────╮
   │                                            │
   │   Nuxt @ v2.15.4                           │
   │                                            │
   │   ▸ Environment: development               │
   │   ▸ Rendering:   server-side               │
   │   ▸ Target:      server                    │
   │                                            │
   │   Listening: http://192.168.5.103:39761/   │
   │                                            │
   │   ⚡  Vite Mode Enabled (v0.1.1)           │
   │                                            │
   ╰────────────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                                                                                  11:31:25
ℹ Initial build may take a while                                                                                                                                                                                                     11:31:25
✔ Builder initialized                                                                                                                                                                                                                11:31:25
✔ Nuxt files generated                                                                                                                                                                                                               11:31:27
 > node_modules/vite/dist/node/chunks/dep-fc2895ac.js:38154:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json.
    38154 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:38154:15)
    at tryNodeResolve (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:37973:11)
    at Context.resolveId (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:37856:28)
    at Object.resolveId (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:50279:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:74236:27
    at async /home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:72051:34
    at async callback (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/esbuild/lib/main.js:812:28)
    at async handleRequest (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/esbuild/lib/main.js:644:30)

   node_modules/vite/dist/node/chunks/dep-fc2895ac.js:72038:18: note: This error came from the "onResolve" callback registered here
    72038 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind, resolveDir }) => {
          ╵                   ~~~~~~~~~
    at setup (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:72038:19)
    at handlePlugins (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/esbuild/lib/main.js:736:23)
    at Object.buildOrServe (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/esbuild/lib/main.js:1024:7)
    at /home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/esbuild/lib/main.js:1750:17
    at new Promise (<anonymous>)
    at Object.build (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/esbuild/lib/main.js:1749:14)
    at Object.build (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/esbuild/lib/main.js:1625:51)
    at optimizeDeps (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:72268:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOptimize (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:72852:48)
    at async Object.createServer (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/vite/dist/node/chunks/dep-fc2895ac.js:72881:9)
    at async buildClient (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js:106:22)
    at async bundle (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js:459:3)
    at async Builder.build (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/@nuxt/builder/dist/builder.js:327:5)
    at async Object._buildDev (/home/kanagu/Desktop/portal/test/vite-nuxt/node_modules/@nuxt/cli/dist/cli-dev.js:107:5)

   node_modules/node-gyp-build/index.js:1:17: note: The plugin "vite:dep-pre-bundle" was triggered by this import
        1 │ var fs = require('fs')
          ╵                  ~~~~


 ERROR  Build failed with 1 error:                                                                                                                                                                                                   11:31:31
node_modules/vite/dist/node/chunks/dep-fc2895ac.js:38154:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json.

  node_modules/vite/dist/node/chunks/dep-fc2895ac.js:38154:14: error: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json.
  at failureErrorWithLog (node_modules/esbuild/lib/main.js:1449:15)
  at node_modules/esbuild/lib/main.js:1131:28
  at runOnEndCallbacks (node_modules/esbuild/lib/main.js:921:63)
  at buildResponseToResult (node_modules/esbuild/lib/main.js:1129:7)
  at node_modules/esbuild/lib/main.js:1236:14
  at node_modules/esbuild/lib/main.js:609:9
  at handleIncomingPacket (node_modules/esbuild/lib/main.js:706:9)
  at Socket.readFromStdout (node_modules/esbuild/lib/main.js:576:7)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:467:12)
  at addChunk (internal/streams/readable.js:309:12)
  at readableAddChunk (internal/streams/readable.js:284:9)
  at Socket.Readable.push (internal/streams/readable.js:223:10)
  at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by lukaszarpak** [comment]
Any update on this issue? I experience the same thing

**Comment by antfu** [comment]
Close due to inactive. If it still persist, please open another issue with proper reproduction.

**Comment by huchangfa123** [comment]
have the same problem. 
![image](https://user-images.githubusercontent.com/20489087/130556626-558e27bd-803e-4a18-8e32-24a649ae5021.png)
while using this package https://www.npmjs.com/package/css

**Comment by pi0** [comment]
Last case for `fs`, is mostly due to using incompatible (node based) library for client-side bundle, but I think since webpack4 is already stubbing built-ins, we might do the same for for vite.

**Comment by spencerbug** [comment]
I am also running into this same thing, any updates on this?

**Comment by aahellokitty** [comment]
请问这个问题有人解决了吗

**Comment by aahellokitty** [comment]
请问有人解决这个问题了吗~

**Comment by aahellokitty** [comment]
有人解决了这个问题嘛

**Comment by jamiehaywood** [comment]
so I had this issue when requiring a [mock-service-worker](https://mswjs.io/) package which is technically isomorphic, but has a bunch of node dependencies (chokidar, node-fetch etc.)

To fix with vite:
1. `yarn add -D rollup-plugin-node-builtins`
2. In your `vite.config.ts` you need to add the following (I've commented the ones I used and just left fs uncommented for this use case specifically):
```ts
resolve: {
  alias: {
    fs: require.resolve('rollup-pligin-node-builtins'),
    // http: require.resolve('rollup-plugin-node-builtins'),
    // util: require.resolve('rollup-plugin-node-builtins'),
    // stream: require.resolve('rollup-plugin-node-builtins'),
    // buffer: require.resolve('rollup-plugin-node-builtins'),
    // process: require.resolve('rollup-plugin-node-builtins'),
    // url: require.resolve('rollup-plugin-node-builtins'),
    // querystring: require.resolve('rollup-plugin-node-builtins'),
  },
},
```
3. 💰

**Comment by yogarasu** [comment]
@jamiehaywood

After yarn add, I wrote the settings, but I get an error.
```
Cannot find module 'rollup-pligin-node-builtins'
```

**Comment by degueba** [comment]
Hey guys, any updates on this issue?
![image](https://user-images.githubusercontent.com/17730060/164546645-a4701c32-5abc-4aa0-b950-ab7f9b1ad058.png)

**Comment by georgeportillo** [comment]
I have the same issue as well:
<img width="1728" alt="Screen Shot 2022-04-23 at 5 49 35 PM" src="https://user-images.githubusercontent.com/1437282/164950993-a3d00e61-16e6-4ea6-b6b6-0e6761a73de1.png">

Any help with this would be appreciated

**Comment by MackDevelops** [comment]
same issue as well, using Quasar Framework, my colleague couldn't replicate it as well, tried matching node, npm and package.json versions.

![80434a544bcdedfc8ca93092f148c33](https://user-images.githubusercontent.com/96734020/167179570-a4048bdc-3b02-4487-8ffe-88db4c68aed8.png)

**Comment by MarcosMRod** [comment]
I had to keep trying to build and add one by one all the node native packages that aws needs in the *alias* field of the **vite.config.ts** , this was the result for my project to work:
`ts
  resolve: {
    alias: {
      '.runtimeConfig': './runtimeConfig.browser',
      http: require.resolve('rollup-plugin-node-builtins'),
      path: require.resolve('rollup-plugin-node-builtins'),
      fs: require.resolve('rollup-plugin-node-builtins'),
      os: require.resolve('rollup-plugin-node-builtins'),
      tslib: require.resolve('rollup-plugin-node-builtins'),
      child_process: require.resolve('rollup-plugin-node-builtins'),
      crypto: require.resolve('rollup-plugin-node-builtins'),
      stream: require.resolve('rollup-plugin-node-builtins'),
      https: require.resolve('rollup-plugin-node-builtins'),
      http2: require.resolve('rollup-plugin-node-builtins'),
      process: require.resolve('rollup-plugin-node-builtins'),
    },
  },
`

**Comment by anish-lakkapragada** [comment]
@jamiehaywood @MarcosMRod, what happens if require is not defined (using module not cjs)? Could be dumb question

**Comment by nathanchi** [comment]
supporting Anish — I face this issue as well
