### ISSUE TITLE
Nuxt CompositionAPI  Support

### ISSUE THREAD

**Issue by humiyan02** [nuxt/vite#17]
An error occerred with using composition API together.
```
  ERROR  Client compiled with errors: Build failed with 39 errors:                                  11:42:15
node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
...

  node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
  node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
  node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
  node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
  node_modules/vite/dist/node/chunks/dep-00e79b84.js:33860:7: error: [vite:dep-scan] No known conditions for "." entry in "@nuxtjs/composition-api" package
  ...
  at failureErrorWithLog (node_modules/esbuild/lib/main.js:1171:15)
  at buildResponseToResult (node_modules/esbuild/lib/main.js:907:32)
  at node_modules/esbuild/lib/main.js:1002:20
  at node_modules/esbuild/lib/main.js:553:9
  at handleIncomingPacket (node_modules/esbuild/lib/main.js:642:9)
  at Socket.readFromStdout (node_modules/esbuild/lib/main.js:520:7)
  at Socket.emit (events.js:315:20)
  at Socket.EventEmitter.emit (domain.js:483:12)
  at addChunk (_stream_readable.js:295:12)
  at readableAddChunk (_stream_readable.js:271:9)
  at Socket.Readable.push (_stream_readable.js:212:10)
  at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)

```

**Comment by vinayakkulkarni** [comment]
nuxt/composition-api is a must!

I'll take a dive deep in the source

**Comment by productfrontenddeveloper** [comment]
Will it come soon

**Comment by danielroe** [comment]
Feel free to try out a WIP version of `@nuxtjs/composition-api` with support for vite following the instructions in the PR: https://github.com/nuxt-community/composition-api/pull/387 (with feedback directly on that PR, please).

**Comment by productfrontenddeveloper** [comment]
@danielroe which one ? 
![Screen Shot 2021-03-03 at 15 21 40](https://user-images.githubusercontent.com/38668796/109805155-28d31d80-7c34-11eb-9208-f01fcb3c0128.png)
