### ISSUE TITLE
builder.bundleBuilder.close is not a function error occurring.

### ISSUE THREAD

**Issue by CodyBontecou** [nuxt/vite#205]
### Versions

nuxt-vite: 0.2.4
nuxt: 2.14.6

### Reproduction

This project - https://github.com/CodyBontecou/testing-nuxts-components-with-storybook-and-cypress - has the issue. Clone it and run `yarn storybook`

### Description

No real issue that I see is coming from this, but I consistently see this error occurring in my terminal.

```
✔ Builder initialized

 FATAL  builder.bundleBuilder.close is not a function

  at fn (node_modules/nuxt-vite/dist/nuxt-vite.js:61:27)
  at fn (node_modules/hable/src/hable.js:63:45)
  at name (node_modules/hable/src/utils.js:15:67)
  at Nuxt.callHook (node_modules/hable/src/hable.js:59:22)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:316:5)

✔ Nuxt files generated
```

**Comment by kovan** [comment]
any updates on this?
