### ISSUE TITLE
Dev Server crashes with error

### ISSUE THREAD

**Issue by IshanKBG** [nuxt/vite#213]
### Versions

nuxt-vite: 0.3.1
nuxt: 2.15.7

### Reproduction
Tried clean installing 
Error is caused when running `yarn dev`
[repo](https://github.com/IshanKBG/ishankbg-web)
### Description

Whenever i run the local dev server with nuxt-vite i get this error
```error
require() of ES Module /home/ishan/ishan-projects/ishankbg/node_modules/p-debounce/index.js from /home/ishan/ishan-projects/ishankbg/node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js not supported.
Instead change the require of index.js in /home/ishan/ishan-projects/ishankbg/node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js to a dynamic import() which is available in all CommonJS modules.

  Instead change the require of index.js in node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js to a dynamic import() which is available in all CommonJS modules.
  at Object.<anonymous> (node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js:10:19)
  at node_modules/nuxt-vite/dist/nuxt-vite.js:56:79
  at async node_modules/nuxt-vite/dist/nuxt-vite.js:56:29


   ╭──────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                          │
   │   ✖ Nuxt Fatal Error                                                                     │
   │                                                                                          │
   │   Error [ERR_REQUIRE_ESM]: require() of ES Module                                        │
   │   /home/ishan/ishan-projects/ishankbg/node_modules/p-debounce/index.js from              │
   │   /home/ishan/ishan-projects/ishankbg/node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js   │
   │   not supported.                                                                         │
   │   Instead change the require of index.js in                                              │
   │   /home/ishan/ishan-projects/ishankbg/node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js   │
   │   to a dynamic import() which is available in all CommonJS modules.                      │
   │                                                                                          │
   ╰──────────────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Before upgrading it was working fine but now i am getting this error.

**Comment by toniengelhardt** [comment]
Same issue.

**Comment by pi0** [comment]
Hi, @IshanKBG Issue related to p-debounce is resolved in `nuxt-vite@^0.3.2`. However, in your reproduction, there seems another issue seems related to the content module:

```
Cannot find module 'html' from '/tmp/ishankbg-web'
Object.$id_882dd793 [as /node_modules/property-information/index.js]
Object.$id_1aea1528 [as /.nuxt/content/nuxt-content.js]
```


@toniengelhardt Would you please upgrade to `0.3.2` to see if solved your issue and creating a new issue with reproduction info if still having issues with 0.3.x?

**Comment by pi0** [comment]
Closing second issue in favor of #215

**Comment by toniengelhardt** [comment]
Upgrading resolved it for me @pi0 thanks!
