### ISSUE TITLE
Undefined `importedModules` on nuxt-vite warmup! 

### ISSUE THREAD

**Issue by ms-fadaei** [nuxt/vite#223]
### Versions

nuxt-vite: 0.3.5
nuxt: 2.16.0-27226092.034b9901

### Reproduction
I know what is the problem. By just adding `buildDir: "something-differnt"` to any existing project you got the error. 

### Description
I use `nuxt-bridge` with `vite: true`.
When I want to start dev I got the error:

```
ERROR  Cannot read property 'importedModules' of undefined
  at warmup (node_modules/nuxt-vite/dist/nuxt-vite.cjs-vite.js:647:71)
  at async Promise.all (index 0)
  at async warmupViteServer (node_modules/nuxt-vite/dist/nuxt-vite.cjs-vite.js:650:3)
```

**Comment by ms-fadaei** [comment]
DEPRECATED module
