### ISSUE TITLE
Failed to resolve entry for package "tty"

### ISSUE THREAD

**Issue by axwalker** [nuxt/vite#26]
I've tried adding nuxt/vite to an existing project but am getting the below error when running `nuxt dev`. I've tried stripping my project down to the bare minimum but still get the error, so I'm not sure what exactly it could be related to. I don't reference the [`tty` node package](https://nodejs.org/api/tty.html) anywhere in my own code.

```
> node_modules/vite/dist/node/chunks/dep-00e79b84.js:34318:14: error: [vite:dep-pre-bundle] Failed to resolve entry for package "tty". The package may have incorrect main/module/exports specified in its package.json.
    34318 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/stuff/frontend/node_modules/vite/dist/node/chunks/dep-00e79b84.js:34318:15)
    at tryNodeResolve (/Users/stuff/frontend/node_modules/vite/dist/node/chunks/dep-00e79b84.js:34158:11)

   node_modules/vite/dist/node/chunks/dep-00e79b84.js:67463:18: note: This error came from the "onResolve" callback registered here
    67463 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer }) => {
          ╵                   ~~~~~~~~~
    at setup (/Users/stuff/frontend/node_modules/vite/dist/node/chunks/dep-00e79b84.js:67463:19)
    at handlePlugins (/Users/stuff/frontend/node_modules/esbuild/lib/main.js:670:7)


 ERROR  1:34:58 PM [vite] error while updating dependencies:                                                                                                                                                                                             13:34:58
Error: Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-00e79b84.js:34318:14: error: [vite:dep-pre-bundle] Failed to resolve entry for package "tty". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/stuff/frontend/node_modules/esbuild/lib/main.js:1171:15)
    at buildResponseToResult (/Users/stuff/frontend/node_modules/esbuild/lib/main.js:907:32)
    at /Users/stuff/frontend/node_modules/esbuild/lib/main.js:1002:20
    at /Users/stuff/frontend/node_modules/esbuild/lib/main.js:553:9
    at handleIncomingPacket (/Users/stuff/frontend/node_modules/esbuild/lib/main.js:642:9)
    at Socket.readFromStdout (/Users/stuff/frontend/node_modules/esbuild/lib/main.js:520:7)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

nuxt/vite version: 0.0.6
nuxt version: 2.15.2

**Comment by pi0** [comment]
Hi @axwalker. Why would you need tyy in nuxt app bundle? Also a small reproduction would be awesome :)

**Comment by maunier** [comment]
Have you resolved this?

**Comment by haikyuu** [comment]
The error comes from `import createDebug from 'debug'` https://github.com/vitest-dev/vitest/blob/main/packages/vite-node/src/hmr/hmr.ts#L4

Don't know the reason, I was hacking around the codebase, and it turned out to be the culprit
