### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by productfrontenddeveloper** [nuxt/vite#28]
### Version
nuxt-vite:  v0.0.7
nuxt: v2.14.12 -->

### Configuration

```export default {
  // Disable server-side rendering (https://go.nuxtjs.dev/ssr-mode)
  ssr: true,
  // Global page headers (https://go.nuxtjs.dev/config-head)
  head: {
    title: 'su',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  // Global CSS (https://go.nuxtjs.dev/config-css)
  css: ['~/assets/css/tailwind.scss'],
  server: {
    host: '0.0.0.0',
    port: process.env.NODE_ENV === 'production' ? '4010' : '3333',
  },
  // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [
    '~/plugins/filters.js',
    '~/plugins/v-tooltip.js',
    '~/plugins/axios.js',
    { src: '~/plugins/vue-form-wizard.js' },
    { src: '~/plugins/vue-js-toggle-button.js', ssr: false },
    { src: '~/plugins/lottie-animation.js' },
    { src: '~/plugins/v-emoji-picker.js' },
    { src: '~/plugins/vee-validate.js', ssr: false },
    { src: '~/plugins/i18n.js' },
  ],

  // Auto import components (https://go.nuxtjs.dev/config-components)
  components: true,

  // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
    'nuxt-ackee',
    'nuxt-vite',
  ],

  // Modules (https://go.nuxtjs.dev/config-modules)
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    // https://go.nuxtjs.dev/content
    // '@nuxt/content',
    '@nuxtjs/auth-next',
    '@nuxtjs/toast',
    '@nuxtjs/proxy',
    [
      'nuxt-i18n',
      {
        lazy: true,
        loadLanguagesAsync: true,
        locales: [
          {
            code: 'en',
            name: 'English',
            iso: 'en-US',
            file: 'en.js',
          },
        ],
        langDir: 'locales/',
        defaultLocale: 'en',
        fallbackLocale: 'en',
        strategy: 'prefix',
        detectBrowserLanguage: {
          useCookie: true,
          cookieKey: 'i18n_redirected',
        },
      },
    ],
    'vue-swatches/nuxt',
  ],
  // Content module configuration (https://go.nuxtjs.dev/config-content)
  content: {},

  axios: {
    proxy: process.env.GENERAL_PROXY || false,
  },


  auth: {
    plugins: ['~/plugins/auth.js'],
    strategies: {
      local: {
        token: {
          property: 'accessToken',
          type: 'Bearer',
        },
        user: {
          property: 'user',
          autoFetch: true,
        },
        endpoints: {
          login: {
            url: '/auth/signin',
            method: 'post',
          },
          logout: {
            url: '/auth/logout',
            method: 'post',
          },
          user: {
            url: '/user/me',
            method: 'get',
          },
        },
      },
    },
  },



  // Build Configuration (https://go.nuxtjs.dev/config-build)
  build: {},
}
``` 

### Description

<img width="1382" alt="Screen Shot 2021-02-26 at 17 06 10" src="https://user-images.githubusercontent.com/38668796/109310049-1aac8800-7855-11eb-93e2-fee3049c8d2e.png">

and terminal
```
 ERROR  ENOENT: no such file or directory, rmdir '/project/node_modules/.vite/temp'                                            17:01:10

  at Proxy.rmdirSync (fs.js:890:10)
  at scanImports (node_modules/vite/dist/node/chunks/dep-00e79b84.js:46058:17)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at doBuild (node_modules/vite/dist/node/chunks/dep-00e79b84.js:46427:41)
  at Object.build (node_modules/vite/dist/node/chunks/dep-00e79b84.js:46379:16)
  at FSWatcher.<anonymous> (node_modules/nuxt-vite/dist/nuxt-vite.js-vite.js:164:5)
```

**Comment by pi0** [comment]
Hi. Store support added in 0.0.9.

**Comment by productfrontenddeveloper** [comment]
hi, I can't test it, I have to wait for the tailwind nuxt library to be updated and I have to upgrade to nuxt 2.15. :D 

```disabling nuxt-vite since nuxt >= 2.15.2 is required (curret version: v2.14.12) ```
