### ISSUE TITLE
`kebab-case` middleware file triggers build error

### ISSUE THREAD

**Issue by tuanna-hsp** [nuxt/vite#36]
### Versions

nuxt-vite: 0.0.12
nuxt: 2.15.2

### Reproduction
Reproduction repository
https://github.com/tuanna-hsp/nuxt-vite-issue

### Description
Can not start nuxt-vite app with `kebab-case` middleware files.
```
ℹ Preparing project for development                                                                                                                                                          00:25:45
ℹ Initial build may take a while                                                                                                                                                             00:25:45
ℹ Discovered Components: .nuxt/components/readme.md                                                                                                                                          00:25:45
✔ Builder initialized                                                                                                                                                                        00:25:45
✔ Nuxt files generated                                                                                                                                                                       00:25:45
✔ Client compiled successfully in 0.015s                                                                                                                                                     00:25:45
 > .nuxt/middleware.js:1:13: error: Expected "from" but found "-"
    1 │ import $kebab-case-middleware from '../middleware/kebab-case-middleware.js'
      ╵              ^


 ERROR  Server compiled with errors: Build failed with 1 error:                                                                                                                              00:25:46
.nuxt/middleware.js:1:13: error: Expected "from" but found "-"

  .nuxt/middleware.js:1:13: error: Expected "from" but found "-"
  at failureErrorWithLog (node_modules/esbuild/lib/main.js:1177:15)
  at buildResponseToResult (node_modules/esbuild/lib/main.js:913:32)
  at node_modules/esbuild/lib/main.js:1008:20
  at node_modules/esbuild/lib/main.js:559:9
  at handleIncomingPacket (node_modules/esbuild/lib/main.js:648:9)
  at Socket.readFromStdout (node_modules/esbuild/lib/main.js:526:7)
  at Socket.emit (events.js:315:20)
  at addChunk (_stream_readable.js:300:12)
  at readableAddChunk (_stream_readable.js:276:9)
  at Socket.Readable.push (_stream_readable.js:217:10)
  at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by pi0** [comment]
Thanks for report. Should be fixed in v13
