### ISSUE TITLE
Cannot find module './mock/web-streams-polyfill' 

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt/vite#46]
### Versions

nuxt-vite: ^0.0.16
nuxt: ^2.14.12

### Reproduction

https://github.com/florian-lefebvre/nuxt-vite-issues-46

### Description

In SSR mode, it takes as much time to build as if the module wasn't there.

**Comment by florian-lefebvre** [comment]
My bad I didn't see it requires Nuxt 2.15

**Comment by florian-lefebvre** [comment]
It would also be good to highlight it in the documentation.

**Comment by florian-lefebvre** [comment]
Hovewer I encountered another issue:
```bash
 ERROR  Cannot find module './mock/web-streams-polyfill'                                                                                                                                                      22:54:01  
Require stack:
- F:\CONTENT\DEVELOPPEMENT\WEB\TESTS\reproduction repos\nuxt-vite-issues-46\node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js
- F:\CONTENT\DEVELOPPEMENT\WEB\TESTS\reproduction repos\nuxt-vite-issues-46\node_modules\nuxt-vite\dist\nuxt-vite.js
- F:\CONTENT\DEVELOPPEMENT\WEB\TESTS\reproduction repos\nuxt-vite-issues-46\node_modules\@nuxt\core\dist\core.js

  Require stack:
  - node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js
  - node_modules\nuxt-vite\dist\nuxt-vite.js
  - node_modules\@nuxt\core\dist\core.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
  at Function.a [as resolve] (node_modules\jiti\dist\v8cache.js:2:2400)
  at bundle (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:245:59)
  at ViteBuilder.build (node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:284:12)
  at Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:30)
  at async Object._buildDev (node_modules\@nuxt\cli\dist\cli-dev.js:107:5)
  at async Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:65:7)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)
```

**Comment by pi0** [comment]
Can you please try v17? :D Sorry i'm iterating fast some regressions happen in between

**Comment by florian-lefebvre** [comment]
It works now 👍
