### ISSUE TITLE
Error: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by thomas4Bitcraft** [nuxt/vite#84]
### Versions

nuxt-vite: 0.0.28
nuxt: 2.15.2

### Reproduction

1. Install nuxt/vite using npm
2. import it in build modules
3. run `npm run dev`

### Description
I tried to add nuxt/vite to an existing project an received following error while building:

FATAL  The "path" argument must be of type string. Received type undefined
  at validateString (internal/validators.js:112:11)
  at extname (path.js:1231:5)
  at l (node_modules/jiti/dist/jiti.js:1:8009)
  at Resolver.p [as _require] (node_modules/jiti/dist/jiti.js:1:8505)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:182:38)
  at node_modules/@nuxt/utils/dist/utils.js:638:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)

**Comment by danielroe** [comment]
@thomas4Bitcraft Would you provide a reproduction please? 🙏

**Comment by antfu** [comment]
Close due to inactive
