### ISSUE TITLE
Unknown word

### ISSUE THREAD

**Issue by Cosbgn** [nuxt/vite#85]
I'm testing `nuxt-vite` but I'm having problems to get it to work with TailwindCSS (but maybe the issue is the same with other css libraries). When I run `npm run dev` I get:

```
ERROR  [vite:css] postcss-import: /Users/c/me/app/node_modules/tailwindcss/lib/index.js:1:1: Unknown word                    

ERROR  file: /Users/c/me/app/assets/tailwind.css                                

ERROR  Server compiled with errors: postcss-import: /Users/c/me/app/node_modules/tailwindcss/lib/index.js:1:1: Unknown word

  at Input.error (node_modules/vite/node_modules/postcss/lib/input.js:113:16)
  at Parser.unknownWord (node_modules/vite/node_modules/postcss/lib/parser.js:518:22)
  at Parser.other (node_modules/vite/node_modules/postcss/lib/parser.js:149:12)
  ```

**Comment by danielroe** [comment]
@Cosbgn Would you provide a reproduction please? 🙏
