### ISSUE TITLE
vue and vuex dependencies no installed

### ISSUE THREAD

**Issue by sternelee** [nuxt/vite#89]
### Versions

nuxt-vite: 0.0.29
nuxt: 2.15.2

### Reproduction
```bash
 ERROR  Client compiled with errors: The following dependencies are imported but could not be resolved:

  vue (imported by D:/www/xunlei/pan.xunlei.com/store/drive.js)
  unfetch (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/client.js)
  vuex (imported by D:/www/xunlei/pan.xunlei.com/components/web/Qrcode.vue)
  vue-meta (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/index.js)
  vue-client-only (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/index.js)
  vue-no-ssr (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/index.js)
  vue-router (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/router.js)
  axios (imported by D:/www/xunlei/pan.xunlei.com/api/get-pub-key.esm.js)

Are they installed?


  vue (imported by D:/www/xunlei/pan.xunlei.com/store/drive.js)
  unfetch (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/client.js)
  vuex (imported by D:/www/xunlei/pan.xunlei.com/components/web/Qrcode.vue)
  vue-meta (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/index.js)
  vue-client-only (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/index.js)
  vue-no-ssr (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/index.js)
  vue-router (imported by D:/www/xunlei/pan.xunlei.com/.nuxt/router.js)
  axios (imported by D:/www/xunlei/pan.xunlei.com/api/get-pub-key.esm.js)

  Are they installed?
  at optimizeDeps (node_modules\.pnpm\vite@2.0.5\node_modules\vite\dist\node\chunks\dep-e0f09032.js:67754:15)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at runOptimize (node_modules\.pnpm\vite@2.0.5\node_modules\vite\dist\node\chunks\dep-e0f09032.js:68328:48)
  at Object.createServer (node_modules\.pnpm\vite@2.0.5\node_modules\vite\dist\node\chunks\dep-e0f09032.js:68356:9)
  at buildClient (node_modules\.pnpm\nuxt-vite@0.0.29\node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:63:22)
  at callBuild (node_modules\.pnpm\nuxt-vite@0.0.29\node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:383:7)
  at async Promise.all (index 0)
  at bundle (node_modules\.pnpm\nuxt-vite@0.0.29\node_modules\nuxt-vite\dist\nuxt-vite.js-vite.js:391:5)
  at Builder.build (node_modules\.pnpm\@nuxt\builder@2.15.2\node_modules\@nuxt\builder\dist\builder.js:327:5)
```

**Comment by sternelee** [comment]
E.g: I use Vue.set in store.js, so
```javascript
import Vue from 'vue'
```

**Comment by sternelee** [comment]
> I mean a sample project on GitHub that can reproduce the issue.

just init nuxt and add nuxt-vite

The reproduction repo is here: https://github.com/sternelee/vite-nuxt

**Comment by pi0** [comment]
Hi @sternelee thanks for repro. It seems you are pnp which is not tested and supported for nuxt/vite. I have esclated this to #91 for supporting pnpm and plug-and-play
